name: Generar Animación de Serpiente

on:
  schedule:
    - cron: "0 */12 * * *" # Se ejecuta cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: BrayanEstevezC
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - name: Subir a la rama output
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
